# Generated by Django 5.1.3 on 2024-11-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=100, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
