# Generated by Django 4.2.17 on 2024-12-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=4),
            preserve_default=False,
        ),
    ]
