# Generated by Django 4.2.17 on 2024-12-10 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_order_quantity_orderline_alter_order_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='line',
        ),
    ]
