# Generated by Django 4.2.17 on 2024-12-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_order_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='line',
            field=models.ManyToManyField(to='store.product'),
        ),
        migrations.DeleteModel(
            name='Orderline',
        ),
    ]
